export const ActionType = {
   BLOG_MODEL_OPEN:'BLOG_MODEL_OPEN',
   BLOG_MODEL_CLOSE:'BLOG_MODEL_CLOSE',

   BLOG_SEC_ADD:'BLOG_SEC_ADD',
   BLOG_SEC_CLEAR:'BLOG_SEC_CLEAR',

   BLOG_DATA_ADD: 'BLOG_DATA_ADD',
   BLOG_DATA_UPDATE_SEC:'BLOG_DATA_UPDATE_SEC',
   BLOG_DATA_UPDATE_REMOVE_SEC:'BLOG_DATA_UPDATE_REMOVE_SEC',
   BLOG_DATA_UPDATE_REMOVE_TAG:'BLOG_DATA_UPDATE_REMOVE_TAG',
   BLOG_DATA_ADD_TAG:'BLOG_DATA_ADD_TAG',

   BLOG_DATA_ADD_CONTENT :'BLOG_DATA_ADD_CONTENT',
   BLOG_EDIT:'BLOG_EDIT',
   LOGIN_FORM_OPEN:'LOGIN_FORM_OPEN',
   LOGIN_FORM_CLOSE:'LOGIN_FORM_CLOSE',
   USER_FETCH:'USER_FETCH',
   USER_CLEAR:'USER_CLEAR'
}