export const ActionType = {
   BLOG_MODEL_OPEN:'BLOG_MODEL_OPEN',
   BLOG_MODEL_CLOSE:'BLOG_MODEL_CLOSE',

   BLOG_SEC_ADD:'BLOG_SEC_ADD',
   BLOG_SEC_CLEAR:'BLOG_SEC_CLEAR',

   BLOG_DATA_ADD: 'BLOG_DATA_ADD',
   BLOG_DATA_UPDATE_SEC:'BLOG_DATA_UPDATE_SEC',
   BLOG_DATA_UPDATE_REMOVE_SEC:'BLOG_DATA_UPDATE_REMOVE_SEC',
   BLOG_DATA_UPDATE_REMOVE_TAG:'BLOG_DATA_UPDATE_REMOVE_TAG',
   BLOG_DATA_ADD_TAG:'BLOG_DATA_ADD_TAG',

   BLOG_DATA_ADD_CONTENT :'BLOG_DATA_ADD_CONTENT',
   BLOG_EDIT:'BLOG_EDIT',
   LOGIN_FORM_OPEN:'LOGIN_FORM_OPEN',
   LOGIN_FORM_CLOSE:'LOGIN_FORM_CLOSE',
   USER_FETCH:'USER_FETCH',
   USER_CLEAR:'USER_CLEAR',

   ADMIN_FILEMANAGER_OPEN:'ADMIN_FILEMANAGER_OPEN',
   ADMIN_FILEMANAGER_CLOSE:'ADMIN_FILEMANAGER_CLOSE',
   SPINNER_OPEN:'SPINNER_OPEN',
   SPINNER_CLOSE:'SPINNER_CLOSE',
   COMPANY_INFO_FETCH:'COMPANY_INFO_FETCH',
   COMPANY_INFO_LOST:'COMPANY_INFO_LOST',

   ADMIN_LOGIN_TOKEN : 'ADMIN_LOGIN_TOKEN',
   ADMIN_LOGIN_LOST : 'ADMIN_LOGIN_LOST'
}